# Global configuration
baseurl: "/blog"
url: "https://skielred.github.io"
timezone: Europe/Paris

# Vars
title: Tina's blog
email: skielred@gmail.com
description: >-
    A simple blog about programming, life in France, rhythm games and life.
twitter_username: Shookaite
github_username:  skielred
discord_username: Tina#4153

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

